version: '3.1'

services:

  nginx:
    build: ./docker/Nginx
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: ./docker/Php
    volumes:
      - ./web:/var/www/html


  fussballinfos:
    image: mysql
    ports:
      - 33060:3306
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: fussballInsight
      MYSQL_USER: asdf
      MYSQL_PASSWORD: asdf

volumes:
  dbdata: